### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by RedlineReform** [DazoTrove/TroveTools.NET#31] opened 2016-08-22 05:39 UTC
[This](http://i.imgur.com/paTmYjw.png) has been happening to me, no clue how to fix it. I had fixed it temporarily at one point then it started happening again. No clue what I did to fix it the first time.
![this shit](https://cloud.githubusercontent.com/assets/19865073/17844622/46357060-6809-11e6-9a23-01e9d88ecbfe.png)

**Comment by DazoTrove** [comment] 2016-08-23 16:18
Try the [troubleshooting steps](https://github.com/DazoTrove/TroveTools.NET#troubleshooting) that I have just added to this project's readme.

**Comment by DazoTrove** [comment] 2016-08-31 06:34
@RedlineReform Let me know whether the troubleshooting steps I linked above worked to fix your issue. If I don't hear back from you by 9/1/2016, I will close this issue since I have been unable to reproduce this specific ClickOnce deployment error message.

**Comment by RedlineReform** [comment] 2016-08-31 19:41
I ended reading one of your other troubleshooting threads. You helped someone clear their %localappdata%, So i gave that a try. Worked like a charm. All good ^_^

**Closed as completed** 2016-08-31 19:42 UTC
Labels: ClickOnce deployment
